doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%dev(MONGODB_SERVER)%'
            options:
              username: '%dev(MONGODB_USER)%'
              password: '%dev(MONGODB_PASS)%'
              db: '%dev(MONGODB_USER)%'
              authSource : '%dev(MONGODB_DBNAME)%'
    default_database: '%dev(MONGODB_DBNAME)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: App\Document\
                    alias: App
#            metadata_cache_driver:
#              type: memcache
#              class : Doctrine\Common\Cache\MemcacheCache
#              host : localhost
#              port : 11211
#              instance_class : Memcache

